############################# English ############################
[en]
languageName = "En"
title = "Circuit Chef"
contentDir = "content/english" # content/english
weight = 0
########### footer content ##########
#footer_menu_left = "Information"
footer_content = "Socials:"