# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Goals"
url = "goals/"
weight = 2

[[main]]
name = "Features"
url = "#Features"
weight = 3

[[main]]
name = "Github"
url = "contact/"
weight = 4